[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/basel-stadt"
  to = "/de/basel-stadt"
  status = 301

[[redirects]]
  from = "/basel-landschaft"
  to = "/de/basel-landschaft"
  status = 301

[[redirects]]
  from = "/faq"
  to = "/de/faq"
  status = 301

[[redirects]]
  from = "/kontakt"
  to = "/de/kontakt"
  status = 301

[[redirects]]
  from = "/so-funktioniert-es"
  to = "/de/so-funktioniert-es"
  status = 301

[[redirects]]
  from = "/antrag"
  to = "/de/antrag"
  status = 301

[[redirects]]
  from = "/impressum"
  to = "/de/impressum"
  status = 301

[[redirects]]
  from = "/datenschutz"
  to = "/de/datenschutz"
  status = 301

[[redirects]]
  from = "/danke"
  to = "/danke"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/:canton"
  to = "/de/:canton"
  status = 301

